mcp:
  servers:
    supabase:
      command: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-supabase"
      cwd: .
      env:
        SUPABASE_URL: "<YOUR_SUPABASE_URL>"
        SUPABASE_KEY: "<YOUR_SUPABASE_API_KEY>"

    whatsapp:
      command: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-whatsapp"
      cwd: .
      env:
        WHATSAPP_API_KEY: "<YOUR_WHATSAPP_API_KEY>"
        WHATSAPP_PHONE_ID: "<YOUR_WHATSAPP_PHONE_ID>"
        WHATSAPP_RECIPIENT_PHONE: "<RECIPIENT_PHONE_FOR_TEST>"
